# Generated by Django 4.2.7 on 2024-04-29 19:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BilligAddress',
            new_name='BillingAddress',
        ),
    ]
